Repository ByteOps-swe/Sorgente-documenti, pull requests merged in 2023-12, with the labels that each got.

#206 eseguito refactoring e fix errori latex
  RTB/Piano_di_progetto_v0.0.4.tex
  RTB/Sezioni/Piano_di_progetto/Analisi_dei_rischi.tex
  RTB/Sezioni/Piano_di_progetto/Calendario_del_progetto.tex
  RTB/Sezioni/Piano_di_progetto/Introduzione.tex
  RTB/Sezioni/Piano_di_progetto/Pianificazione_preventivo_consuntivo.tex
  RTB/Sezioni/Piano_di_progetto/Stima_dei_costi_realizzazione.tex
  RTB/Sottosezioni/Piano_di_progetto/Consuntivo.tex
  RTB/Sottosezioni/Piano_di_progetto/Descrizione.tex
  RTB/Sottosezioni/Piano_di_progetto/Gestione_e_monitoraggio.tex
  RTB/Sottosezioni/Piano_di_progetto/Glossario.tex
  RTB/Sottosezioni/Piano_di_progetto/Introduzione_calendario.tex
  RTB/Sottosezioni/Piano_di_progetto/Introduzione_stima.tex
  RTB/Sottosezioni/Piano_di_progetto/Pianificazione.tex
  RTB/Sottosezioni/Piano_di_progetto/Preventivo.tex
  RTB/Sottosezioni/Piano_di_progetto/Prima_stesura_calendario.tex
  RTB/Sottosezioni/Piano_di_progetto/Prima_stesura_stima.tex
  RTB/Sottosezioni/Piano_di_progetto/Processo_di_mitigazione.tex
  RTB/Sottosezioni/Piano_di_progetto/Requirements_technology_baseline.tex
  RTB/Sottosezioni/Piano_di_progetto/Riferimenti.tex
  RTB/Sottosezioni/Piano_di_progetto/Rischi_previsti.tex
  RTB/Sottosezioni/Piano_di_progetto/Scopo_del_capitolato.tex
  RTB/Sottosezioni/Piano_di_progetto/Scopo_del_documento.tex
  RTB/Sottosezioni/Piano_di_progetto/Seconda_stesura_stima.tex
Labels: PianoDiProgetto

#207 pubblicazione in documents
  RTB/Verbali/Esterni/Verbale_10-11-2023.tex
Labels: Verbale

#211 Versione aggiornata action
  .github/workflows/main.yml
  Version_finder.py
Labels: bug

#209 NdP verifica
  RTB/Norme_di_progetto_v0.3.0.tex
  RTB/Sottosezioni/Norme_di_progetto/Verifica.tex
Labels: NormeDiProgetto

#213 NdP joint review
  RTB/Sezioni/Norme_di_progetto/Processi_di_supporto.tex
  RTB/Sottosezioni/Norme_di_progetto/JointReview.tex
  RTB/Sottosezioni/Norme_di_progetto/Risoluzione_dei_problemi.tex
Labels: NormeDiProgetto

#210 Glossario
  RTB/Glossario_v0.0.1.tex
Labels: documentation

#216 pubblicazione verbale
  RTB/Verbali/Interni/Verbale_04-12-2023.tex
Labels: Verbale

#217 eliminata cartella documents
  Documents/Candidatura/Lettera di Presentazione.tex
  Documents/Candidatura/Preventivo costi e assunzione impegni.tex
  Documents/Candidatura/Valutazione Capitolati.tex
  Documents/Images/logo.png
  Documents/RTB/Norme di progetto/Norme di progetto.tex
  Documents/Verbali/Candidatura/Esterni/Verbale 20-10-2023.tex
  Documents/Verbali/Candidatura/Interni/Verbale 17-10-2023.tex
  Documents/Verbali/Candidatura/Interni/Verbale 18-10-2023.tex
  Documents/Verbali/Candidatura/Interni/Verbale 23-10-2023.tex
  Documents/Verbali/Candidatura/Interni/Verbale 27-10-2023.tex
  Documents/Verbali/RTB/Interni/Verbale 03-11-2023.tex
  Documents/template.tex
Labels: bug

#220 Ho aggiunto le metriche e rivisto alcuni punti.
  RTB/Glossario_v0.0.2.tex
Labels: documentation

#221 Tolto il doppione creato erroneamente
  RTB/Glossario_v0.1.0.tex
Labels: documentation

#223 aggiunto metodo di gestione per lo sviluppo
  RTB/Sottosezioni/Norme_di_progetto/Gestione_della_configurazione.tex
Labels: NormeDiProgetto

#225 Verbale Esterno 24-11-2023
  RTB/Verbali/Esterni/Verbale_24-11-2023.tex
Labels: Verbale

#224 Verbale Esterno 07-12-2023
  RTB/Verbali/Esterni/Verbale_07-12-2023.tex
Labels: Verbale

#226 Redazione Analisi dei Requisiti sezione Sviluppo
  Images/NormeDiProgetto/ClassDiagram_Aggregazione.PNG
  Images/NormeDiProgetto/ClassDiagram_Associazione.PNG
  Images/NormeDiProgetto/ClassDiagram_Composizione.PNG
  Images/NormeDiProgetto/ClassDiagram_Dipendenza.PNG
  Images/NormeDiProgetto/ClassDiagram_Generalizzazione.PNG
  Images/NormeDiProgetto/InterfaceRealization.PNG
  RTB/Norme_di_progetto_v0.4.0.tex
  RTB/Sottosezioni/Norme_di_progetto/Sviluppo.tex
Labels: documentation, NormeDiProgetto, Verifica

#227 Aggiunta codifica dei rischi
  RTB/Sottosezioni/Norme_di_progetto/Risoluzione_dei_problemi.tex
Labels: documentation, NormeDiProgetto

#228 PdP - Secondo periodo
  Images/avanzamento2Periodo.png
  Images/consuntivoDivisioneRuoli2Periodo.png
  Images/consuntivoOrario2Periodo.png
  Images/periodo1.PNG
  Images/periodo1.jpg
  Images/periodo2.PNG
  Images/preventivoDivisioneRuoli2Periodo.png
  Images/preventivoOrario2Periodo.png
  RTB/Piano_di_progetto_v0.2.0.tex
  RTB/Sezioni/Piano_di_progetto/Pianificazione_preventivo_consuntivo.tex
  RTB/Sottosezioni/Piano_di_progetto/Gestione_e_monitoraggio.tex
  RTB/Sottosezioni/Piano_di_progetto/Pianificazione.tex
  RTB/Sottosezioni/Piano_di_progetto/Requirements_technology_baseline.tex
  RTB/Sottosezioni/Piano_di_progetto/Rischi_previsti.tex
Labels: documentation, PianoDiProgetto

#229 Redazione sezione Standard Qualità
  RTB/Norme_di_progetto_v0.5.0.tex
  RTB/Sezioni/Norme_di_progetto/StandardQualità.tex
  RTB/Sottosezioni/Norme_di_progetto/ISO25010.tex
Labels: documentation, NormeDiProgetto

#230 NdP - Metriche qualità
  RTB/Norme_di_progetto_v0.5.0.tex
  RTB/Sezioni/Norme_di_progetto/Metriche_di_qualita.tex
Labels: documentation, NormeDiProgetto

#231 revisione finale
  RTB/Verbali/Esterni/Verbale_24-11-2023.tex
Labels: documentation, Verbale

#232 VE_07-12-2023
  RTB/Verbali/Esterni/Verbale_07-12-2023.tex
Labels: documentation, Verbale

#233 aggiunto verbali esterni a eccezioni
  .github/workflows/main.yml
Labels: enhancement, Actions

#237 VI 08/12/2023
  RTB/Verbali/Interni/Verbale_08-12-2023.tex
Labels: documentation, Verbale

#238 Cambio nome del verbale Part 1
  Candidatura/Verbali/Interni/Verbale_17-10-2023.tex
  Candidatura/Verbali/Interni/Verbale_18-10-2023.tex
  Candidatura/Verbali/Interni/Verbale_23-10-2023.tex
  Candidatura/Verbali/Interni/Verbale_27-10-2023.tex
Labels: Actions

#239 Cambio nome del verbale Part 2
  Candidatura/Verbali/Interni/Verbale_2023-10-17.tex
  Candidatura/Verbali/Interni/Verbale_2023-10-18.tex
  Candidatura/Verbali/Interni/Verbale_2023-10-23.tex
  Candidatura/Verbali/Interni/Verbale_2023-10-27.tex
  RTB/Verbali/Interni/Verbale_03-11-2023.tex
  RTB/Verbali/Interni/Verbale_04-12-2023.tex
  RTB/Verbali/Interni/Verbale_06-11-2023.tex
  RTB/Verbali/Interni/Verbale_08-12-2023.tex
  RTB/Verbali/Interni/Verbale_17-11-2023.tex
  RTB/Verbali/Interni/Verbale_24-11-2023.tex
Labels: Actions

#244 Verbale interno 15/12/2023
  RTB/Verbali/Interni/Verbale_2023-12-15.tex
Labels: documentation, Verbale

#246 NdP_ModGestioneDellaConfigurazione
  RTB/Sottosezioni/Norme_di_progetto/Gestione_della_configurazione.tex
Labels: documentation, NormeDiProgetto

#250 Cambiato comando per la compilazione di file LaTeX
  .github/workflows/main.yml
Labels: bug, Actions

#251 NdP modifica gestione della config. - sincronizzazione e branching
  RTB/Sottosezioni/Norme_di_progetto/Gestione_della_configurazione.tex
Labels: documentation, NormeDiProgetto

#252 NdP modifica sezione documentazione
  RTB/Norme_di_progetto_v0.5.0.tex
  RTB/Sottosezioni/Norme_di_progetto/Documentazione.tex
Labels: documentation, NormeDiProgetto

#247 PdQ Sezione 2 Refactoring
  RTB/Piano_di_qualifica_v0.0.1.tex
  RTB/Sezioni/Piano_di_qualifica/Introduzione.tex
  RTB/Sezioni/Piano_di_qualifica/Obiettivi_metrici_di_qualità.tex
  RTB/Sezioni/Piano_di_qualifica/PdQ_Test.tex
  RTB/Sezioni/Piano_di_qualifica/Specifica_dei_test.tex
  RTB/Sottosezioni/Piano_di_qualifica/Affidabilita.tex
  RTB/Sottosezioni/Piano_di_qualifica/Copertura_test.tex
  RTB/Sottosezioni/Piano_di_qualifica/Efficienza.tex
  RTB/Sottosezioni/Piano_di_qualifica/Finalità_del_documento.tex
  RTB/Sottosezioni/Piano_di_qualifica/Funzionalita.tex
  RTB/Sottosezioni/Piano_di_qualifica/Glossario.tex
  RTB/Sottosezioni/Piano_di_qualifica/Manutenibilita.tex
  RTB/Sottosezioni/Piano_di_qualifica/Portabilita.tex
  RTB/Sottosezioni/Piano_di_qualifica/Qualità_di_processo.tex
  RTB/Sottosezioni/Piano_di_qualifica/Qualità_di_prodotto.tex
  RTB/Sottosezioni/Piano_di_qualifica/Qualità_per_obiettivo.tex
  RTB/Sottosezioni/Piano_di_qualifica/Riferimenti.tex
  RTB/Sottosezioni/Piano_di_qualifica/Usabilita.tex
Labels: PianoDiQualifica

#248 Aggiornata sezione NdP riguardante PdQ
  RTB/Norme_di_progetto_v0.5.0.tex
  RTB/Sezioni/Norme_di_progetto/Metriche_di_qualita.tex
  RTB/Sezioni/Norme_di_progetto/StandardQualità.tex
  RTB/Sottosezioni/Norme_di_progetto/ISO25010.tex
  RTB/Sottosezioni/Norme_di_progetto/Metriche_per_la_qualità_di_processo.tex
  RTB/Sottosezioni/Norme_di_progetto/Metriche_per_la_qualità_di_prodotto.tex
  RTB/Sottosezioni/Norme_di_progetto/Standard_adottati.tex
Labels: NormeDiProgetto
