Repository ByteOps-swe/Sorgente-documenti, pull requests merged in 2024-03, with the labels that each got.

#357 PdP - Ottavo periodo
  Documenti_Esterni/Piano_di_progetto_v1.0.1.tex
  Documenti_Esterni/Sottosezioni/Piano_di_progetto/Rischi_previsti.tex
  Documenti_Esterni/Sottosezioni/Piano_di_progetto/Tra_rtb_pb.tex
  Documenti_Esterni/Sottosezioni/Piano_di_progetto/Verso_la_product_baseline.tex
  Documenti_Esterni/Sottosezioni/Piano_di_progetto/Verso_la_requirements_technology_baseline.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Risoluzione_dei_problemi.tex
  Documenti_Interni/Verbali/Verbale_2024-02-12.tex
  Images/avanzamento8Periodo.PNG
  Images/avanzamento9Periodo.PNG
  Images/consuntivoDivisioneRuoli8Periodo.PNG
  Images/consuntivoDivisioneRuoli9Periodo.PNG
  Images/consuntivoOrario8Periodo.PNG
  Images/consuntivoOrario9Periodo.png
  Images/periodo8.PNG
  Images/periodo9.png
  Images/preventivoDivisioneRuoli8Periodo.PNG
  Images/preventivoDivisioneRuoli9Periodo.PNG
  Images/preventivoOrario8Periodo.PNG
  Images/preventivoOrario9Periodo.png
Labels: documentation, PianoDiProgetto, Verifica

#358 Aggiunti termini a Glossario, Analisi Requisiti e Verbale
  Documenti_Esterni/Sottosezioni/Analisi_dei_requisiti/Casi_uso/UC34.tex
  Documenti_Esterni/Sottosezioni/Analisi_dei_requisiti/Elenco_dei_casi_duso.tex
  Documenti_Esterni/Sottosezioni/Analisi_dei_requisiti/Requisiti_funzionali.tex
  Documenti_Interni/Glossario_v1.0.0.tex
  Documenti_Interni/Verbali/Verbale_2024-03-01.tex
  Images/UC34.png
  updateGlossario.py
Labels: documentation, Verbale, AnalisiDeiRequisiti

#359 Aggiunte issue mancanti al verbale
  Documenti_Interni/Verbali/Verbale_2024-03-01.tex
Labels: Verbale

#360 correzione verbale
  Documenti_Interni/Verbali/Verbale_2024-03-01.tex
Labels: documentation, Verbale, Verifica

#361 Verbale interno 2024 02 26
  Documenti_Interni/Verbali/Verbale_2024-02-02.tex
  Documenti_Interni/Verbali/Verbale_2024-02-26.tex
Labels: documentation, Verbale, Verifica

#362 Verbale esterno 2024/03/01
  Documenti_Esterni/Verbali/Verbale_2024-03-01.tex
Labels: documentation, Verbale, Verifica

#363 Redazione PdP - Periodo #9
  Documenti_Esterni/Sottosezioni/Piano_di_progetto/Verso_la_product_baseline.tex
Labels: documentation, PianoDiProgetto, Verifica

#364 Ve_2024-03-08
  Documenti_Esterni/Verbali/Verbale_2024-03-08.tex
Labels: documentation, Verbale, Verifica

#365 correzioni VE_2024-03-08
  Documenti_Esterni/Verbali/Verbale_2024-03-08.tex
Labels: documentation, Verbale, Verifica

#366 St impostazione generale
  Images/SpecificaTecnica/ConProjectionRisultato.jpg
  Images/SpecificaTecnica/ProjectionQuery.jpg
  Images/SpecificaTecnica/ProjectionUsedByClickHouse.jpg
  Images/SpecificaTecnica/SenzaProectionResult.jpg
  Images/SpecificaTecnica/architettura.jpg
  Images/SpecificaTecnica/chargingStations.png
  Images/SpecificaTecnica/dust_PM10.png
  Images/SpecificaTecnica/ecoIslands.png
  Images/SpecificaTecnica/electricalFault.png
  Images/SpecificaTecnica/humidity.png
  Images/SpecificaTecnica/kafka_engine_architecture.png
  Images/SpecificaTecnica/query2ProjectionsWith.jpg
  Images/SpecificaTecnica/query2ProjectionsWithout.jpg
  Images/SpecificaTecnica/req_obbligatori.PNG
  Images/SpecificaTecnica/sensorType_kafka.PNG
  Images/SpecificaTecnica/simulatoriSensori.PNG
  Images/SpecificaTecnica/temperatures.PNG
  Images/SpecificaTecnica/temperatures1Mese.PNG
  Images/SpecificaTecnica/temperatures1g.PNG
  Images/SpecificaTecnica/temperatures1m.PNG
  Images/SpecificaTecnica/temperatures1o.PNG
  Images/SpecificaTecnica/temperatures_kafka.PNG
  Images/SpecificaTecnica/waterPresence.png
  PB/Progettazione starUML/innovaCity.mdj
  PB/Sezioni/Specifica_tecnica/Architettura.tex
  PB/Sezioni/Specifica_tecnica/Architetturadeployment.tex
  PB/Sezioni/Specifica_tecnica/Introduzione.tex
  PB/Sezioni/Specifica_tecnica/Tecnologie.tex
  PB/Sezioni/Specifica_tecnica/tabellaRequisiti.tex
  PB/Sottosezioni/Specifica_tecnica/ClickHouse.tex
  PB/Sottosezioni/Specifica_tecnica/Glossario.tex
  PB/Sottosezioni/Specifica_tecnica/Grafana.tex
  PB/Sottosezioni/Specifica_tecnica/Json.tex
  PB/Sottosezioni/Specifica_tecnica/Kafka.tex
  PB/Sottosezioni/Specifica_tecnica/Python.tex
  PB/Sottosezioni/Specifica_tecnica/Riferimenti.tex
  PB/Sottosezioni/Specifica_tecnica/SQL.tex
  PB/Sottosezioni/Specifica_tecnica/Scopo_del_documento.tex
  PB/Sottosezioni/Specifica_tecnica/Scopo_del_progetto.tex
  PB/Sottosezioni/Specifica_tecnica/Yaml.tex
  PB/Sottosezioni/Specifica_tecnica/architetturaSimulatori.tex
  PB/Sottosezioni/Specifica_tecnica/comunicazioneComponenti.tex
  PB/Sottosezioni/Specifica_tecnica/database_config.tex
  PB/Sottosezioni/Specifica_tecnica/faust_processing.tex
  PB/Sottosezioni/Specifica_tecnica/grafana_config.tex
  PB/Sottosezioni/Specifica_tecnica/kafka_config.tex
  PB/Specifica_tecnica.tex
Labels: documentation

#367 cancellate cartelle vecchie, bugfix labels e testo
  Documenti_Interni/Sezioni/Specifica_tecnica/Architettura.tex
  Documenti_Interni/Sezioni/Specifica_tecnica/Architettura_deployment.tex
  Documenti_Interni/Sezioni/Specifica_tecnica/Introduzione.tex
  Documenti_Interni/Sezioni/Specifica_tecnica/Tabella_requisiti.tex
  Documenti_Interni/Sezioni/Specifica_tecnica/Tecnologie.tex
  Documenti_Interni/Sottosezioni/Specifica_tecnica/Architettura_simulatori.tex
  Documenti_Interni/Sottosezioni/Specifica_tecnica/Clickhouse.tex
  Documenti_Interni/Sottosezioni/Specifica_tecnica/Comunicazione_componenti.tex
  Documenti_Interni/Sottosezioni/Specifica_tecnica/Database_config.tex
  Documenti_Interni/Sottosezioni/Specifica_tecnica/Faust_processing.tex
  Documenti_Interni/Sottosezioni/Specifica_tecnica/Glossario.tex
  Documenti_Interni/Sottosezioni/Specifica_tecnica/Grafana.tex
  Documenti_Interni/Sottosezioni/Specifica_tecnica/Grafana_config.tex
  Documenti_Interni/Sottosezioni/Specifica_tecnica/Json.tex
  Documenti_Interni/Sottosezioni/Specifica_tecnica/Kafka.tex
  Documenti_Interni/Sottosezioni/Specifica_tecnica/Kafka_config.tex
  Documenti_Interni/Sottosezioni/Specifica_tecnica/Python.tex
  Documenti_Interni/Sottosezioni/Specifica_tecnica/Riferimenti.tex
  Documenti_Interni/Sottosezioni/Specifica_tecnica/SQL.tex
  Documenti_Interni/Sottosezioni/Specifica_tecnica/Scopo_del_documento.tex
  Documenti_Interni/Sottosezioni/Specifica_tecnica/Scopo_del_progetto.tex
  Documenti_Interni/Sottosezioni/Specifica_tecnica/Yaml.tex
  Documenti_Interni/Specifica_tecnica.tex
  UML_Diagrams/innovaCity.mdj
Labels: documentation

#369 PdP - Redazione decimo periodo
  Documenti_Esterni/Piano_di_progetto_v1.0.2.tex
  Documenti_Esterni/Sottosezioni/Piano_di_progetto/Rischi_previsti.tex
  Documenti_Esterni/Sottosezioni/Piano_di_progetto/Verso_la_product_baseline.tex
  Images/avanzamento10Periodo.PNG
  Images/consuntivoDivisioneRuoli10Periodo.PNG
  Images/consuntivoOrario10Periodo.PNG
  Images/periodo10.PNG
  Images/preventivoDivisioneRuoli10Periodo.PNG
  Images/preventivoOrario10Periodo.PNG
Labels: documentation, PianoDiProgetto, Verifica

#370 modificato changelog e aggiunta nuova immagine architettura
  Documenti_Interni/Sezioni/Specifica_tecnica/Architettura.tex
  Documenti_Interni/Specifica_tecnica_v0.0.1.tex
  Images/SpecificaTecnica/Architettura_PB_microservices2.png
Labels: documentation

#371 PdP - redazione periodo 11
  Documenti_Esterni/Piano_di_progetto_v1.0.4.tex
  Documenti_Esterni/Sottosezioni/Piano_di_progetto/Verso_la_product_baseline.tex
  Images/avanzamento11Periodo.PNG
  Images/consuntivoDivisioneRuoli11Periodo.PNG
  Images/consuntivoOrario11Periodo.PNG
  Images/periodo11.PNG
  Images/preventivoDivisioneRuoli11Periodo.PNG
  Images/preventivoOrario11Periodo.PNG
Labels: documentation, PianoDiProgetto, Verifica

#374 Redazione periodo #12 - PdP
  Documenti_Esterni/Piano_di_progetto_v1.0.5.tex
  Documenti_Esterni/Sottosezioni/Piano_di_progetto/Verso_la_product_baseline.tex
  Images/avanzamento12Periodo.PNG
  Images/consuntivoDivisioneRuoli12Periodo.PNG
  Images/consuntivoOrario12Periodo.jpeg
  Images/periodo12.jpeg
  Images/preventivoDivisioneRuoli12Periodo.PNG
  Images/preventivoOrario12Periodo.jpeg
Labels: documentation, PianoDiProgetto, Verifica

#375 Cambiate immagini e aggiornate in ST
  Images/SpecificaTecnica/chargingStations.png
  Images/SpecificaTecnica/dust_PM10.png
  Images/SpecificaTecnica/ecoIslands.png
  Images/SpecificaTecnica/electricalFault.png
  Images/SpecificaTecnica/humidity.png
  Images/SpecificaTecnica/temperatures.PNG
  Images/SpecificaTecnica/waterPresence.png
Labels: documentation

#376 Modifiche changelog ST
  Documenti_Interni/Specifica_tecnica_v0.4.0.tex
Labels: documentation, Verifica, SpecificaTecnica

#377 Redazione Verbale Esterno 15/03/2024
  Documenti_Esterni/Verbali/Verbale_2024-03-15.tex
Labels: documentation, Verbale, Verifica

#379 Redazione VI 05/03/2024
  Documenti_Interni/Verbali/Verbale_2024-03-01.tex
  Documenti_Interni/Verbali/Verbale_2024-03-05.tex
Labels: documentation, Verbale, Verifica

#380 redazione VE_22-03-2024
  Documenti_Esterni/Verbali/Verbale_2024-03-22.tex
Labels: documentation, Verbale, Verifica

#382 modifica nome file
  Documenti_Esterni/Manuale_utente_v1.0.0.tex
Labels: documentation, ManualeUtente

#383 Aggiunti termini glossario
  Documenti_Interni/Glossario_v1.1.0.tex
  updateGlossario.py
Labels: documentation

#385 Redazione VI 23/03/2024
  Documenti_Interni/Verbali/Verbale_2024-03-05.tex
  Documenti_Interni/Verbali/Verbale_2024-03-23.tex
Labels: documentation, Verbale, Verifica

#387 Modifiche per applicazione script glossario
  Documenti_Esterni/Sezioni/Manuale_utente/Requisiti.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Alert.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Dashboard.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Glossario.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Gruppi_panel.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Login.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Profilo.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Requisiti_Hardware.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Requisiti_Software.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Riferimenti.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Scopo_del_documento.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Scopo_del_prodotto.tex
Labels: documentation, ManualeUtente

#389 aggiustate immagini
  Documenti_Esterni/Sottosezioni/Piano_di_progetto/Tra_rtb_pb.tex
  Images/tabCons12.png
  Images/tabPrev12.png
Labels: documentation, PianoDiProgetto
