Repository ByteOps-swe/Sorgente-documenti, pull requests merged in 2024-02, with the labels that each got.

#288 Aggiunto le sezioni menzionato da AdR
  RTB/Sottosezioni/Analisi_dei_requisiti/Introduzione.tex
  RTB/Sottosezioni/Analisi_dei_requisiti/Requisiti_qualitativi.tex
  RTB/Sottosezioni/Analisi_dei_requisiti/Riferimenti.tex
Labels: documentation, AnalisiDeiRequisiti

#292 Revisionato AdR a versione 1.0.0
  RTB/Analisi_dei_requisiti_v0.8.2.tex
Labels: AnalisiDeiRequisiti

#293 modificata versione riferimenti documenti esterni
  RTB/Sottosezioni/Analisi_dei_requisiti/Introduzione.tex
  RTB/Sottosezioni/Analisi_dei_requisiti/Requisiti_qualitativi.tex
Labels: AnalisiDeiRequisiti

#290 redazione verbale
  RTB/Verbali/Interni/Verbale_2024-01-11.tex
Labels: Verbale

#291 Pdp quinto periodo
  Images/consuntivoDivisioneRuoli5Periodo.png
  Images/consuntivoOrario5Periodo.png
  Images/periodo5.PNG
  Images/preventivoDivisioneRuoli5Periodo.png
  Images/preventivoOrario5Periodo.png
  RTB/Piano_di_progetto_v0.2.5.tex
  RTB/Sottosezioni/Piano_di_progetto/Verso_la_requirements_technology_baseline.tex
Labels: PianoDiProgetto

#298 Aggiunte metriche in tab. e messo apposto changelog Glossario
  RTB/Glossario_v0.0.3.tex
  RTB/Norme_di_progetto_v0.6.0.tex
  RTB/Sottosezioni/Norme_di_progetto/Documentazione.tex
  RTB/Sottosezioni/Norme_di_progetto/Gestione_dei_processi.tex
  RTB/Sottosezioni/Norme_di_progetto/Gestione_della_configurazione.tex
  RTB/Sottosezioni/Norme_di_progetto/Gestione_della_qualita.tex
  RTB/Sottosezioni/Norme_di_progetto/Metriche_per_la_qualità_di_processo.tex
  RTB/Sottosezioni/Norme_di_progetto/Metriche_per_la_qualità_di_prodotto.tex
  RTB/Sottosezioni/Norme_di_progetto/Sviluppo.tex
Labels: NormeDiProgetto

#301 Redatto il verbale del 2 Febbraio
  RTB/Verbali/Interni/Verbale_2024-02-02.tex
Labels: Verbale

#306 Candidatura rtb
  RTB/Candidatura_RTB.tex
Labels: documentation

#309 Ve 09 02 2024
  RTB/Verbali/Esterni/Verbale_2024-02-09.tex
Labels: Verbale

#310 Modifiche al verbale 09-02-2024
  RTB/Verbali/Esterni/Verbale_2024-02-09.tex
Labels: Verbale

#314 modifiche G a VE_09-02-2024
  RTB/Verbali/Esterni/Verbale_2024-02-09.tex
Labels: Verbale

#315 Nuove modifiche VE_09-02-2024
  RTB/Verbali/Esterni/Verbale_2024-02-09.tex
Labels: Verbale

#318 corretto verbale
  RTB/Verbali/Esterni/Verbale_2023-11-10.tex
  RTB/Verbali/Esterni/Verbale_2023-11-24.tex
  RTB/Verbali/Esterni/Verbale_2023-12-07.tex
  RTB/Verbali/Esterni/Verbale_2024-02-09.tex
Labels: documentation, Verbale

#320 Modifiche ai riferimenti dei test di sistema e al changelog
  RTB/Piano_di_qualifica_v0.3.0.tex
  RTB/Sottosezioni/Piano_di_qualifica/Test_di_sistema.tex
Labels: PianoDiQualifica

#321 Modifiche PdP
  RTB/Sezioni/Piano_di_progetto/Analisi_dei_rischi.tex
  RTB/Sezioni/Piano_di_progetto/RetrospettivaGenerale.tex
  RTB/Sottosezioni/Piano_di_progetto/AspettiNegativi.tex
  RTB/Sottosezioni/Piano_di_progetto/AspettiPositivi.tex
  RTB/Sottosezioni/Piano_di_progetto/Consuntivo.tex
  RTB/Sottosezioni/Piano_di_progetto/Descrizione_formato_periodi.tex
  RTB/Sottosezioni/Piano_di_progetto/GestioneRisorse.tex
  RTB/Sottosezioni/Piano_di_progetto/Glossario.tex
  RTB/Sottosezioni/Piano_di_progetto/Introduzione_Analisi_dei_rischi.tex
  RTB/Sottosezioni/Piano_di_progetto/Introduzione_calendario.tex
  RTB/Sottosezioni/Piano_di_progetto/Introduzione_stima.tex
  RTB/Sottosezioni/Piano_di_progetto/Pianificazione.tex
  RTB/Sottosezioni/Piano_di_progetto/Preventivo.tex
  RTB/Sottosezioni/Piano_di_progetto/PreventivoFinire.tex
  RTB/Sottosezioni/Piano_di_progetto/Prima_stesura_calendario.tex
  RTB/Sottosezioni/Piano_di_progetto/Prima_stesura_stima.tex
  RTB/Sottosezioni/Piano_di_progetto/Processo_di_mitigazione.tex
  RTB/Sottosezioni/Piano_di_progetto/Riferimenti.tex
  RTB/Sottosezioni/Piano_di_progetto/Rischi_previsti.tex
  RTB/Sottosezioni/Piano_di_progetto/Scopo_del_capitolato.tex
  RTB/Sottosezioni/Piano_di_progetto/Scopo_del_documento.tex
  RTB/Sottosezioni/Piano_di_progetto/Seconda_stesura_calendario.tex
  RTB/Sottosezioni/Piano_di_progetto/Seconda_stesura_stima.tex
  RTB/Sottosezioni/Piano_di_progetto/Terza_stesura_stima.tex
  RTB/Sottosezioni/Piano_di_progetto/Verso_la_product_baseline.tex
  RTB/Sottosezioni/Piano_di_progetto/Verso_la_requirements_technology_baseline.tex
  updateGlossario.py
Labels: PianoDiProgetto

#323 Impaginato PdP, pronto per release
  Images/PaF1stesura.PNG
  Images/PaF2stesura.PNG
  Images/RiepilogoPrezziRTB.png
  Images/consuntivoDivisioneRuoli5Periodo.png
  Images/consuntivoOrario1Periodo.png
  Images/consuntivoOrario2Periodo.png
  Images/consuntivoOrario3Periodo.png
  Images/consuntivoOrario4Periodo.png
  Images/consuntivoOrario5Periodo.png
  Images/preventivoDivisioneRuoli5Periodo.png
  Images/preventivoOrario1Periodo.png
  Images/preventivoOrario2Periodo.png
  Images/preventivoOrario3Periodo.png
  Images/preventivoOrario4Periodo.png
  Images/preventivoOrario5Periodo.png
  Images/riepilogoRTBOreMembro.png
  Images/spiegazioneTabella.png
  RTB/Piano_di_progetto_v1.0.0.tex
  RTB/Sottosezioni/Piano_di_progetto/Descrizione_formato_periodi.tex
  RTB/Sottosezioni/Piano_di_progetto/GestioneRisorse.tex
  RTB/Sottosezioni/Piano_di_progetto/Pianificazione.tex
  RTB/Sottosezioni/Piano_di_progetto/PreventivoFinire.tex
  RTB/Sottosezioni/Piano_di_progetto/Riferimenti.tex
  RTB/Sottosezioni/Piano_di_progetto/Rischi_previsti.tex
  RTB/Sottosezioni/Piano_di_progetto/Seconda_stesura_calendario.tex
  RTB/Sottosezioni/Piano_di_progetto/Seconda_stesura_stima.tex
  RTB/Sottosezioni/Piano_di_progetto/Terza_stesura_stima.tex
  RTB/Sottosezioni/Piano_di_progetto/Verso_la_product_baseline.tex
  RTB/Sottosezioni/Piano_di_progetto/Verso_la_requirements_technology_baseline.tex
Labels: PianoDiProgetto, Verifica

#326 Preparato PdQ per la release, corretta impaginazione
  RTB/Piano_di_qualifica_v1.0.0.tex
  RTB/Sezioni/Piano_di_qualifica/Cruscotto.tex
  RTB/Sottosezioni/Piano_di_qualifica/Affidabilita.tex
  RTB/Sottosezioni/Piano_di_qualifica/Copertura_test.tex
  RTB/Sottosezioni/Piano_di_qualifica/Efficienza.tex
  RTB/Sottosezioni/Piano_di_qualifica/Funzionalita.tex
  RTB/Sottosezioni/Piano_di_qualifica/Manutenibilita.tex
  RTB/Sottosezioni/Piano_di_qualifica/Portabilita.tex
  RTB/Sottosezioni/Piano_di_qualifica/Qualità_Documentazione.tex
  RTB/Sottosezioni/Piano_di_qualifica/Qualità_Fornitura.tex
  RTB/Sottosezioni/Piano_di_qualifica/Qualità_di_processo.tex
  RTB/Sottosezioni/Piano_di_qualifica/Qualità_di_prodotto.tex
  RTB/Sottosezioni/Piano_di_qualifica/Qualità_per_obiettivo.tex
  RTB/Sottosezioni/Piano_di_qualifica/Riferimenti.tex
  RTB/Sottosezioni/Piano_di_qualifica/Test_di_accettazione.tex
  RTB/Sottosezioni/Piano_di_qualifica/Test_di_sistema.tex
  RTB/Sottosezioni/Piano_di_qualifica/Usabilita.tex
Labels: Verifica, PianoDiQualifica

#328 Revisione finale Norme di Progetto
  RTB/Norme_di_progetto_v0.6.0.tex
  RTB/Sezioni/Norme_di_progetto/Processi_organizzativi.tex
  RTB/Sottosezioni/Norme_di_progetto/Documentazione.tex
  RTB/Sottosezioni/Norme_di_progetto/Finalità_del_documento.tex
  RTB/Sottosezioni/Norme_di_progetto/Formazione.tex
  RTB/Sottosezioni/Norme_di_progetto/Fornitura.tex
  RTB/Sottosezioni/Norme_di_progetto/Gestione_dei_processi.tex
  RTB/Sottosezioni/Norme_di_progetto/Gestione_della_configurazione.tex
  RTB/Sottosezioni/Norme_di_progetto/Gestione_della_qualita.tex
  RTB/Sottosezioni/Norme_di_progetto/JointReview.tex
  RTB/Sottosezioni/Norme_di_progetto/Metriche_per_la_qualità_di_processo.tex
  RTB/Sottosezioni/Norme_di_progetto/Metriche_per_la_qualità_di_prodotto.tex
  RTB/Sottosezioni/Norme_di_progetto/Miglioramento.tex
  RTB/Sottosezioni/Norme_di_progetto/Riferimenti.tex
  RTB/Sottosezioni/Norme_di_progetto/Risoluzione_dei_problemi.tex
  RTB/Sottosezioni/Norme_di_progetto/Standard_adottati.tex
  RTB/Sottosezioni/Norme_di_progetto/Sviluppo.tex
  RTB/Sottosezioni/Norme_di_progetto/Validazione.tex
  RTB/Sottosezioni/Norme_di_progetto/Verifica.tex
Labels: documentation, NormeDiProgetto

#329 Impaginazione finale NdP per revisione RTB
  Images/NormeDiProgetto/Attore.PNG
  Images/NormeDiProgetto/GeneralizzazioneAttori.PNG
  RTB/Norme_di_progetto_v0.6.0.tex
  RTB/Sezioni/Norme_di_progetto/Metriche_di_qualita.tex
  RTB/Sottosezioni/Norme_di_progetto/Documentazione.tex
  RTB/Sottosezioni/Norme_di_progetto/Finalità_del_documento.tex
  RTB/Sottosezioni/Norme_di_progetto/Fornitura.tex
  RTB/Sottosezioni/Norme_di_progetto/Gestione_dei_processi.tex
  RTB/Sottosezioni/Norme_di_progetto/Gestione_della_configurazione.tex
  RTB/Sottosezioni/Norme_di_progetto/Gestione_della_qualita.tex
  RTB/Sottosezioni/Norme_di_progetto/JointReview.tex
  RTB/Sottosezioni/Norme_di_progetto/Metriche_per_la_qualità_di_processo.tex
  RTB/Sottosezioni/Norme_di_progetto/Metriche_per_la_qualità_di_prodotto.tex
  RTB/Sottosezioni/Norme_di_progetto/Miglioramento.tex
  RTB/Sottosezioni/Norme_di_progetto/Riferimenti.tex
  RTB/Sottosezioni/Norme_di_progetto/Risoluzione_dei_problemi.tex
  RTB/Sottosezioni/Norme_di_progetto/Standard_adottati.tex
  RTB/Sottosezioni/Norme_di_progetto/Sviluppo.tex
  RTB/Sottosezioni/Norme_di_progetto/Validazione.tex
  RTB/Sottosezioni/Norme_di_progetto/Verifica.tex
Labels: NormeDiProgetto, Verifica

#331 Update Versione
  RTB/Norme_di_progetto_v0.6.0.tex
Labels: documentation, NormeDiProgetto, Verifica

#330 Correzione finale grafico PdQ
  Images/PianoDiQualifica/BV_SV.png
  RTB/Sottosezioni/Piano_di_qualifica/Qualità_Fornitura.tex
Labels: PianoDiQualifica

#334 Update versione Glossario
  RTB/Glossario_v0.0.5.tex
Labels: documentation, Verifica

#335 Modifica info documento template verbale esterno
  Templates/Verbale_Esterno.tex
Labels: documentation, enhancement, Verifica

#325 stesura 7 periodo
  Images/consuntivoDivisioneRuoli7Periodo.png
  Images/consuntivoOrario7Periodo.png
  Images/periodo7.PNG
  Images/preventivoDivisioneRuoli7Periodo.png
  Images/preventivoOrario7Periodo.png
  RTB/Piano_di_progetto_v1.0.0.tex
  RTB/Sezioni/Piano_di_progetto/Pianificazione_preventivo_consuntivo.tex
  RTB/Sottosezioni/Piano_di_progetto/Consuntivo.tex
  RTB/Sottosezioni/Piano_di_progetto/Descrizione_formato_periodi.tex
  RTB/Sottosezioni/Piano_di_progetto/GestioneRisorse.tex
  RTB/Sottosezioni/Piano_di_progetto/Introduzione_calendario.tex
  RTB/Sottosezioni/Piano_di_progetto/Introduzione_stima.tex
  RTB/Sottosezioni/Piano_di_progetto/Pianificazione.tex
  RTB/Sottosezioni/Piano_di_progetto/Preventivo.tex
  RTB/Sottosezioni/Piano_di_progetto/PreventivoFinire.tex
  RTB/Sottosezioni/Piano_di_progetto/Prima_stesura_calendario.tex
  RTB/Sottosezioni/Piano_di_progetto/Prima_stesura_stima.tex
  RTB/Sottosezioni/Piano_di_progetto/Processo_di_mitigazione.tex
  RTB/Sottosezioni/Piano_di_progetto/Rischi_previsti.tex
  RTB/Sottosezioni/Piano_di_progetto/Seconda_stesura_calendario.tex
  RTB/Sottosezioni/Piano_di_progetto/Tra_rtb_pb.tex
  RTB/Sottosezioni/Piano_di_progetto/Verso_la_product_baseline.tex
  RTB/Sottosezioni/Piano_di_progetto/Verso_la_requirements_technology_baseline.tex
Labels: documentation, PianoDiProgetto, Verifica

#336 Aggiornamento template VE
  Templates/Verbale_Esterno.tex
Labels: documentation, Verbale, Verifica

#316 corr cardin
  RTB/Analisi_dei_requisiti_v1.0.0.tex
  RTB/Sottosezioni/Analisi_dei_requisiti/Casi_uso/UC10.tex
  RTB/Sottosezioni/Analisi_dei_requisiti/Casi_uso/UC2.tex
  RTB/Sottosezioni/Analisi_dei_requisiti/Casi_uso/UC23.tex
  RTB/Sottosezioni/Analisi_dei_requisiti/Casi_uso/UC24.tex
  RTB/Sottosezioni/Analisi_dei_requisiti/Casi_uso/UC25.tex
  RTB/Sottosezioni/Analisi_dei_requisiti/Casi_uso/UC26.tex
  RTB/Sottosezioni/Analisi_dei_requisiti/Casi_uso/UC27.tex
  RTB/Sottosezioni/Analisi_dei_requisiti/Casi_uso/UC28.tex
  RTB/Sottosezioni/Analisi_dei_requisiti/Casi_uso/UC29.tex
  RTB/Sottosezioni/Analisi_dei_requisiti/Elenco_dei_casi_duso.tex
  RTB/Sottosezioni/Analisi_dei_requisiti/Glossario.tex
  RTB/Sottosezioni/Analisi_dei_requisiti/Requisiti_funzionali.tex
  RTB/Sottosezioni/Analisi_dei_requisiti/Requisiti_prestazionali.tex
  RTB/Sottosezioni/Analisi_dei_requisiti/Requisiti_qualitativi.tex
  RTB/Sottosezioni/Analisi_dei_requisiti/Tracciamento.tex
Labels: documentation, AnalisiDeiRequisiti, Verifica

#337 Redazione verbale esterno 16/02/2024
  RTB/Verbali/Esterni/Verbale_2024-02-16.tex
Labels: documentation, Verbale, Verifica

#338 redatto Verbale Esterno 23 febbraio
  PB/Verbali/Esterni/Verbale_2024-02-23.tex
Labels: documentation, Verbale
