Repository ByteOps-swe/Sorgente-documenti, pull requests merged in 2024-04, with the labels that each got.

#401 Aggiunta casi d'uso mancanti
  Documenti_Esterni/Sottosezioni/Analisi_dei_requisiti/Casi_uso/UC34.1.tex
  Documenti_Esterni/Sottosezioni/Analisi_dei_requisiti/Casi_uso/UC34.2.tex
  Documenti_Esterni/Sottosezioni/Analisi_dei_requisiti/Casi_uso/UC34.tex
  Documenti_Esterni/Sottosezioni/Analisi_dei_requisiti/Casi_uso/UC35.tex
  Documenti_Esterni/Sottosezioni/Analisi_dei_requisiti/Elenco_dei_casi_duso.tex
  Images/UC34.png
Labels: documentation, AnalisiDeiRequisiti, Verifica

#403 NdP - Update sez. struttura repo
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Gestione_della_configurazione.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Verifica.tex
Labels: documentation, NormeDiProgetto, Verifica

#408 Aggiunte MU
  Documenti_Esterni/Manuale_utente_v1.0.0.tex
  Documenti_Esterni/Sezioni/Manuale_utente/Glossario.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Alert.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Glossario.tex
  Documenti_Interni/Glossario_v2.0.0.tex
Labels: documentation, Verifica, ManualeUtente

#409 Aggiornato glossario
  Documenti_Esterni/Manuale_utente_v1.0.0.tex
  Documenti_Esterni/Sezioni/Manuale_utente/Glossario.tex
  Documenti_Esterni/Sezioni/Manuale_utente/Istruzioni_uso.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Dashboard.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Glossario.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Profilo.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Requisiti_Hardware.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Requisiti_Software.tex
Labels: documentation, Verifica, ManualeUtente

#411 NdP - sistemato riferimenti
  Documenti_Interni/Norme_di_progetto_v2.0.0.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Documentazione.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Finalità_del_documento.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Fornitura.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Gestione_dei_processi.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Gestione_della_configurazione.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Gestione_della_qualita.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Glossario.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/JointReview.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Miglioramento.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Riferimenti.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Risoluzione_dei_problemi.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Standard_adottati.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Sviluppo.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Validazione.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Verifica.tex
Labels: documentation, NormeDiProgetto, Verifica

#412 redazione LP
  Lettera_di_presentazione_PB.tex
Labels: documentation, Verifica

#413 Check versioni doc
  Documenti_Esterni/Analisi_dei_requisiti_v2.0.0.tex
  Documenti_Esterni/Manuale_utente_v1.0.0.tex
  Documenti_Esterni/Sezioni/Manuale_utente/Introduzione.tex
  Documenti_Esterni/Sottosezioni/Analisi_dei_requisiti/Glossario.tex
  Documenti_Esterni/Sottosezioni/Analisi_dei_requisiti/Introduzione.tex
  Documenti_Esterni/Sottosezioni/Analisi_dei_requisiti/Riferimenti.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Alert.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Gruppi_panel.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Profilo.tex
  Documenti_Esterni/Sottosezioni/Manuale_utente/Riferimenti.tex
  Documenti_Esterni/Sottosezioni/Piano_di_progetto/AspettiPositivi.tex
  Documenti_Esterni/Sottosezioni/Piano_di_progetto/Glossario.tex
  Documenti_Esterni/Sottosezioni/Piano_di_progetto/Riferimenti.tex
  Documenti_Esterni/Sottosezioni/Specifica_tecnica/Glossario.tex
  Documenti_Esterni/Sottosezioni/Specifica_tecnica/Riferimenti.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Fornitura.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Riferimenti.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Sviluppo.tex
  Lettera_di_presentazione_PB.tex
Labels: documentation, Verifica

#415 PdQ - update
  Documenti_Esterni/Manuale_utente_v1.0.0.tex
  Documenti_Esterni/Piano_di_qualifica_v1.0.0.tex
  Documenti_Esterni/Sezioni/Piano_di_qualifica/Cruscotto.tex
  Documenti_Esterni/Sezioni/Piano_di_qualifica/Obiettivi_metrici_di_qualità.tex
  Documenti_Esterni/Sezioni/Piano_di_qualifica/Specifica_dei_test.tex
  Documenti_Esterni/Sottosezioni/Piano_di_qualifica/Glossario.tex
  Documenti_Esterni/Sottosezioni/Piano_di_qualifica/Qualità_AR.tex
  Documenti_Esterni/Sottosezioni/Piano_di_qualifica/Qualità_Documentazione.tex
  Documenti_Esterni/Sottosezioni/Piano_di_qualifica/Qualità_Fornitura.tex
  Documenti_Esterni/Sottosezioni/Piano_di_qualifica/Qualità_Verifica.tex
  Documenti_Esterni/Sottosezioni/Piano_di_qualifica/Qualità_di_processo.tex
  Documenti_Esterni/Sottosezioni/Piano_di_qualifica/Qualità_per_obiettivo.tex
  Documenti_Esterni/Sottosezioni/Piano_di_qualifica/Riferimenti.tex
  Documenti_Esterni/Sottosezioni/Piano_di_qualifica/Test_di_accettazione.tex
  Documenti_Esterni/Sottosezioni/Piano_di_qualifica/Test_di_sistema.tex
  Documenti_Esterni/Sottosezioni/Piano_di_qualifica/Test_di_unità.tex
  Images/PianoDiQualifica/AC_ETC.png
  Images/PianoDiQualifica/BV_SV.png
  Images/PianoDiQualifica/EV_PV.png
  Images/PianoDiQualifica/Gulpease.png
  Images/PianoDiQualifica/M11RNP.png
  Images/PianoDiQualifica/M13PCTS.png
  Images/PianoDiQualifica/M14PCTF.png
  Images/PianoDiQualifica/M15SC.png
  Images/PianoDiQualifica/M16BC.png
  Images/PianoDiQualifica/M1PMS.png
  Images/PianoDiQualifica/M24DE.png
  Images/PianoDiQualifica/M2EAC.png
  Images/PianoDiQualifica/M3CPI.png
  Images/PianoDiQualifica/PRDS.png
  Images/PianoDiQualifica/PROS.png
  Images/PianoDiQualifica/PRPS.png
  Images/PianoDiQualifica/errori_ortografici.png
Labels: documentation, Verifica, PianoDiQualifica

#417 Piccoli fix impaginazione
  Documenti_Esterni/Piano_di_progetto_v2.0.0.tex
  Documenti_Esterni/Sezioni/Piano_di_progetto/Pianificazione_preventivo_consuntivo.tex
  Documenti_Esterni/Sezioni/Piano_di_qualifica/Specifica_dei_test.tex
  Documenti_Esterni/Sottosezioni/Analisi_dei_requisiti/Glossario.tex
  Documenti_Esterni/Sottosezioni/Analisi_dei_requisiti/Riferimenti.tex
  Documenti_Esterni/Sottosezioni/Analisi_dei_requisiti/Scopo_del_documento.tex
  Documenti_Esterni/Sottosezioni/Piano_di_progetto/Descrizione_formato_periodi.tex
  Documenti_Esterni/Sottosezioni/Piano_di_progetto/Verso_la_product_baseline.tex
  Documenti_Esterni/Sottosezioni/Piano_di_progetto/Verso_la_requirements_technology_baseline.tex
  Documenti_Esterni/Sottosezioni/Piano_di_qualifica/Glossario.tex
  Documenti_Esterni/Sottosezioni/Specifica_tecnica/Glossario.tex
  Documenti_Esterni/Sottosezioni/Specifica_tecnica/Scopo_del_documento.tex
  Documenti_Interni/Glossario_v2.0.0.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Fornitura.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Gestione_della_configurazione.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Gestione_della_qualita.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Glossario.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Sviluppo.tex
  Documenti_Interni/Sottosezioni/Norme_di_progetto/Verifica.tex
  Documenti_Interni/Verbali/Verbale_2024-02-26.tex
  Documenti_Interni/Verbali/Verbale_2024-03-23.tex
  Lettera_di_presentazione_PB.tex
Labels: documentation, Verifica
