Repository ByteOps-swe/Sorgente-documenti, pull requests merged in 2024-01, with the labels that each got.

#274 Ritoccate formule per metriche processi
  RTB/Sezioni/Piano_di_qualifica/Introduzione 2.tex
  RTB/Sezioni/Piano_di_qualifica/Obiettivi_metrici_di_qualità 2.tex
  RTB/Sezioni/Piano_di_qualifica/Specifica_dei_test 2.tex
  RTB/Sottosezioni/Norme_di_progetto/Metriche_per_la_qualità_di_processo.tex
Labels: NormeDiProgetto

#277 PdQ configuration template
  RTB/Piano_di_qualifica_v0.2.0.tex
  RTB/Sezioni/Piano_di_qualifica/Obiettivi_metrici_di_qualità.tex
  RTB/Sezioni/Piano_di_qualifica/Specifica_dei_test.tex
  RTB/Sottosezioni/Piano_di_qualifica/Test_di_accettazione.tex
  RTB/Sottosezioni/Piano_di_qualifica/Test_di_sistema.tex
Labels: PianoDiQualifica

#279 Non aveva aggiunto le modifiche l'ultimo commit
  RTB/Sottosezioni/Norme_di_progetto/Metriche_per_la_qualità_di_processo.tex
Labels: NormeDiProgetto

#282 Update Verbale_2024-01-05.tex
  RTB/Verbali/Interni/Verbale_2024-01-05.tex
Labels: documentation, Verbale
